# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import will_common.utils.fileds


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColMeta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tbl_type', models.CharField(max_length=30, null=True)),
                ('col_type_name', models.CharField(max_length=300, null=True)),
                ('col_comment', models.CharField(max_length=300, null=True)),
                ('col_name', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'col_tbl_db_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DB',
            fields=[
                ('db_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=4000)),
                ('db_location_uri', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=128)),
                ('owner_name', models.CharField(max_length=128)),
                ('owner_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'DBS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL',
            fields=[
                ('tbl_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('create_time', will_common.utils.fileds.Long2Date()),
                ('owner', models.CharField(max_length=767)),
                ('tbl_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'TBLS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('meta', models.CharField(max_length=20)),
                ('tblName', models.CharField(db_column=b'tbl_name', max_length=30)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('preSql', models.TextField(blank=True, db_column=b'pre_sql', null=True)),
                ('ctime', models.DateTimeField(default=datetime.datetime(2016, 8, 19, 6, 18, 21, 541933, tzinfo=utc))),
                ('priority', models.IntegerField(blank=True, default=5)),
                ('onSchedule', models.IntegerField(db_column=b'on_schedule', default=1)),
                ('valid', models.IntegerField(default=1)),
                ('setting', models.CharField(default=b'', max_length=200)),
                ('variables', models.CharField(default=b'', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Executions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.ETL')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=30, unique=True)),
                ('db', models.CharField(max_length=30)),
                ('settings', models.CharField(max_length=300, null=True)),
                ('type', models.IntegerField(default=1)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TblBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblName', models.CharField(db_column=b'tbl_name', max_length=30)),
                ('parentTbl', models.CharField(db_column=b'parent_tbl', max_length=30)),
                ('relatedEtlId', models.IntegerField(db_column=b'related_etl_id')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tblblood',
            unique_together=set([('tblName', 'parentTbl', 'valid')]),
        ),
    ]
