# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 10, 45, 55, 401034, tzinfo=utc)),
        ),
    ]
