# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0002_auto_20160705_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 11, 41, 30, 147100, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tblblood',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 11, 41, 30, 164096, tzinfo=utc)),
        ),
    ]
