# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0003_auto_20160824_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 11, 32, 50, 419620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tblblood',
            name='tblName',
            field=models.CharField(db_column=b'tbl_name', max_length=100),
        ),
    ]
