# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0003_auto_20160705_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='setting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etl',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tblblood',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='tblblood',
            unique_together=set([('tblName', 'parentTbl', 'valid')]),
        ),
    ]
