# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('metamap', '0004_auto_20160824_1932'),
    ]

    operations = [
    ]
