# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0004_auto_20160721_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl',
            name='setting',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
