# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0005_auto_20160721_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=50)),
                ('jobId', models.IntegerField(db_column=b'job_id')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
