# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0006_auto_20160901_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='willdependencytask',
            name='utime',
            field=models.DateTimeField(null=True),
        ),
    ]
