# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0006_executions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etl',
            name='priority',
            field=models.IntegerField(blank=True, default=5, max_length=4),
        ),
        migrations.AlterField(
            model_name='executions',
            name='status',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='tblblood',
            name='valid',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
