# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0007_auto_20160901_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('headers', models.TextField()),
                ('query', models.TextField()),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('utime', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(blank=True, default=5)),
                ('valid', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='willdependencytask',
            name='rel_id',
            field=models.IntegerField(help_text=b'ETL or Email id', null=True),
        ),
        migrations.AddField(
            model_name='willdependencytask',
            name='type',
            field=models.IntegerField(default=1, help_text=b'1 ETL; 2 EMAIL;'),
        ),
        migrations.AlterField(
            model_name='willdependencytask',
            name='valid',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='willdependencytask',
            name='etl',
        ),
        migrations.AlterUniqueTogether(
            name='willdependencytask',
            unique_together=set([('rel_id', 'schedule')]),
        ),
    ]
