# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0007_auto_20160725_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='variables',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='etl',
            name='priority',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='executions',
            name='logLocation',
            field=models.CharField(db_column=b'log_location', max_length=120),
        ),
        migrations.AlterField(
            model_name='executions',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tblblood',
            name='valid',
            field=models.IntegerField(default=1),
        ),
    ]
