# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0011_exports'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaetl',
            name='auth_users',
            field=models.TextField(default=b''),
        ),
    ]
