# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0012_anaetl_auth_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sys_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SqoopHive2Mysql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'none', max_length=40)),
                ('columns', models.TextField(null=True)),
                ('update_key', models.TextField(null=True)),
                ('update_mode', models.CharField(default=b'allowinsert', max_length=30)),
                ('query', models.TextField(null=True)),
                ('mysql_tbl', models.CharField(max_length=300)),
                ('option', models.TextField(null=True)),
                ('parallel', models.IntegerField(default=1, verbose_name=b'\xe5\xb9\xb6\xe5\x8f\x91\xe6\x89\xa7\xe8\xa1\x8c')),
                ('hive_meta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2m_h', to='metamap.Meta')),
                ('mysql_meta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2m_m', to='metamap.Meta')),
            ],
        ),
        migrations.CreateModel(
            name='SqoopMysql2Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.TextField(null=True)),
                ('query', models.TextField(null=True)),
                ('mysql_tbl', models.CharField(max_length=300)),
                ('option', models.TextField(null=True)),
                ('hive_meta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='m2h_h', to='metamap.Meta')),
                ('mysql_meta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='m2h_m', to='metamap.Meta')),
            ],
        ),
        migrations.AlterField(
            model_name='etl',
            name='tblName',
            field=models.CharField(db_column=b'tbl_name', max_length=100, verbose_name='ETL\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='valid',
            field=models.IntegerField(default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        )
    ]
