# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0013_auto_20161206_1101'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='WillDependencyTask',
        # ),
        # migrations.RemoveField(
        #     model_name='sqoophive2mysql',
        #     name='query',
        # ),
        # migrations.AddField(
        #     model_name='sqoophive2mysql',
        #     name='hive_tbl',
        #     field=models.CharField(default=-999, max_length=300),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='exports',
        #     name='task',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.WillDependencyTask'),
        # ),
    ]
