# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0014_auto_20161207_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='partion_expr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
