# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0016_auto_20161207_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqoopHive2MysqlExecutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='WillDependencyTask',
        # ),
        # migrations.RemoveField(
        #     model_name='sqoophive2mysql',
        #     name='query',
        # ),
        # migrations.AddField(
        #     model_name='sqoophive2mysql',
        #     name='hive_tbl',
        #     field=models.CharField(default=b'none', max_length=300),
        # ),
        # migrations.AlterField(
        #     model_name='exports',
        #     name='task',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.WillDependencyTask'),
        # ),
        migrations.AddField(
            model_name='sqoophive2mysqlexecutions',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.SqoopHive2Mysql'),
        ),
    ]
