# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0019_sqoophive2mysql_ctime'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='WillDependencyTask',
        # ),
        # migrations.RemoveField(
        #     model_name='sqoophive2mysql',
        #     name='query',
        # ),
        # migrations.AddField(
        #     model_name='sqoophive2mysql',
        #     name='hive_tbl',
        #     field=models.CharField(default=b'none', max_length=300),
        # ),
        # migrations.AlterField(
        #     model_name='exports',
        #     name='task',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.WillDependencyTask'),
        # ),
    ]
