# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0020_auto_20161209_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqoopMysql2HiveExecutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RenameField(
            model_name='sqoopmysql2hive',
            old_name='query',
            new_name='where_clause',
        ),
        migrations.RemoveField(
            model_name='sqoophive2mysql',
            name='update_mode',
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='name',
            field=models.CharField(default=b'none', max_length=40),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='parallel',
            field=models.IntegerField(default=1, verbose_name=b'\xe5\xb9\xb6\xe5\x8f\x91\xe6\x89\xa7\xe8\xa1\x8c'),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hiveexecutions',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.SqoopMysql2Hive'),
        ),
    ]
