# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0002_auto_20161219_0819'),
        ('metamap', '0023_auto_20161219_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaetl',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ana_creator', to='will_common.UserProfile'),
        ),
        migrations.AddField(
            model_name='etl',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_creator', to='will_common.UserProfile'),
        ),
        migrations.AddField(
            model_name='meta',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meta_creator', to='will_common.UserProfile'),
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2m_creator', to='will_common.UserProfile'),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m2h_creator', to='will_common.UserProfile'),
        ),
    ]
