# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('metamap', '0024_auto_20161219_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='crete_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_creator', to='auth.Group'),
        ),
    ]
