# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('metamap', '0025_etl_crete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etl',
            name='crete_group',
        ),
        migrations.AddField(
            model_name='anaetl',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ana_cgroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='etl',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_cgroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='meta',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meta_cgroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2m_cgroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m2h_cgroup', to='auth.Group'),
        ),
    ]
