# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0028_auto_20170227_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5f15\u64ce\u540d\u79f0')),
                ('bin_name', models.CharField(max_length=20, verbose_name='\u5f15\u64ce\u542f\u52a8\u811a\u672c')),
                ('enpath_path', models.CharField(max_length=300, verbose_name='\u5f15\u64ce\u8def\u5f84')),
            ],
        ),
        migrations.RenameField(
            model_name='sourceapp',
            old_name='engine_type',
            new_name='engine_type_id',
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='setting',
            field=models.TextField(default=b'', max_length=200, verbose_name='\u8fd0\u884c\u53c2\u6570'),
        ),
    ]
