# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0031_auto_20170228_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5f15\u64ce\u540d\u79f0')),
                ('bin_name', models.CharField(max_length=20, verbose_name='\u5f15\u64ce\u542f\u52a8\u811a\u672c')),
                ('enpath_path', models.CharField(max_length=300, verbose_name='\u5f15\u64ce\u8def\u5f84')),
            ],
        ),
    ]
