# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0033_auto_20170228_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceapp',
            name='compile_tool_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.CompileTool', verbose_name='\u8fd0\u884c\u5de5\u5177'),
        ),
    ]
