# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0034_auto_20170228_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceapp',
            old_name='compile_tool_id',
            new_name='compile_tool',
        ),
    ]
