# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0035_auto_20170228_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAppExecutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='sourceapp',
            name='main_func',
            field=models.CharField(default='sd', max_length=100, verbose_name='\u5165\u53e3\u7c7b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceappexecutions',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.SourceApp'),
        ),
    ]
