# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0036_auto_20170228_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiletool',
            name='opts',
            field=models.CharField(default='target', max_length=100, verbose_name='\u9ed8\u8ba4\u7f16\u8bd1\u53c2\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiletool',
            name='target_path',
            field=models.CharField(default='target', max_length=100, verbose_name='\u9ed8\u8ba4\u76ee\u6807\u6587\u4ef6\u8def\u5f84'),
            preserve_default=False,
        ),
    ]
