# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0037_auto_20170228_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceapp',
            name='setting',
        ),
        migrations.AddField(
            model_name='sourceapp',
            name='engine_opts',
            field=models.TextField(blank=True, default=b'', max_length=400, null=True, verbose_name='\u5f15\u64ce\u8fd0\u884c\u53c2\u6570'),
        ),
        migrations.AddField(
            model_name='sourceapp',
            name='main_func_opts',
            field=models.TextField(blank=True, default=b'', max_length=400, null=True, verbose_name='\u5165\u53e3\u7c7b\u8fd0\u884c\u53c2\u6570'),
        ),
    ]
