# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0002_auto_20161219_0819'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('metamap', '0038_auto_20170228_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('main_func', models.CharField(max_length=100, verbose_name='\u5165\u53e3\u7c7b')),
                ('priority', models.IntegerField(blank=True, default=5)),
                ('valid', models.IntegerField(default=1, verbose_name='\u662f\u5426\u751f\u6548')),
                ('engine_opts', models.TextField(blank=True, default=b'', max_length=400, null=True, verbose_name='\u5f15\u64ce\u8fd0\u884c\u53c2\u6570')),
                ('main_func_opts', models.TextField(blank=True, default=b'', max_length=400, null=True, verbose_name='\u5165\u53e3\u7c7b\u8fd0\u884c\u53c2\u6570')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jar_cgroup', to='auth.Group')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jar_creator', to='will_common.UserProfile')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.SourceEngine', verbose_name='\u8fd0\u884c\u5de5\u5177')),
            ],
        ),
        migrations.CreateModel(
            name='JarAppExecutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logLocation', models.CharField(db_column=b'log_location', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.JarApp')),
            ],
        ),
    ]
