# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0039_jarapp_jarappexecutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarapp',
            name='jar_file',
            field=models.FileField(default='/tmp', upload_to=b'.'),
            preserve_default=False,
        ),
    ]
