# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0002_auto_20161219_0819'),
        ('metamap', '0041_auto_20170306_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarappexecutions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jar_owner', to='will_common.UserProfile'),
        ),
        migrations.AddField(
            model_name='jarappexecutions',
            name='pid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='engine_opts',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u5f15\u64ce\u8fd0\u884c\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='main_func',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name='\u5165\u53e3\u7c7b'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='main_func_opts',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u5165\u53e3\u7c7b\u8fd0\u884c\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='engine_opts',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u5f15\u64ce\u8fd0\u884c\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='main_func_opts',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u5165\u53e3\u7c7b\u8fd0\u884c\u53c2\u6570'),
        ),
    ]
