# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0042_auto_20170418_1034'),
    ]
    #
    # operations = [
    #     migrations.AlterField(
    #         model_name='etl',
    #         name='cgroup',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_cgroup', to='will_common.OrgGroup'),
    #     ),
    # ]
