# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0043_auto_20170510_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaetl',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ana_cgroup', to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jar_cgroup', to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meta_cgroup', to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_cgroup', to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sqoophive2mysql',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2m_cgroup', to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sqoopmysql2hive',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m2h_cgroup', to='will_common.OrgGroup'),
        ),
    ]
