# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0003_auto_20170510_0822'),
        ('metamap', '0044_auto_20170510_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExecObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'name', max_length=100)),
                ('type', models.IntegerField(default=1, help_text=b'1 ETL; 2 EMAIL; 3 Hive2Mysql; 4 Mysql2Hive; 5 sourcefile;6 jarfile')),
                ('rel_id', models.IntegerField()),
                ('cgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_v2_cgroup', to='will_common.OrgGroup')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etl_v2_creator', to='will_common.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='anaetl',
            name='utime',
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='priority',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='priority',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AddField(
            model_name='etlblood',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='etlblood',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='metamap.ExecObj'),
        ),
    ]
