# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0045_auto_20170517_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etl',
            name='tblName',
        ),
        migrations.AddField(
            model_name='etl',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='anaetl',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='anaetl',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='anaetl',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='anaetl',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='jar_file',
            field=models.FileField(blank=True, upload_to=b'jars'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='valid',
            field=models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548'),
        ),
        migrations.AlterField(
            model_name='sqoophive2mysql',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sqoophive2mysql',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sqoophive2mysql',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sqoopmysql2hive',
            name='cgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup'),
        ),
        migrations.AlterField(
            model_name='sqoopmysql2hive',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sqoopmysql2hive',
            name='name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0'),
        ),
    ]
