# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0003_auto_20170510_0822'),
        ('metamap', '0047_auto_20170518_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='NULLETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(blank=True, default=5)),
                ('valid', models.IntegerField(choices=[(1, b'\xe6\x98\xaf'), (0, b'\xe5\x90\xa6')], default=1, verbose_name='\u662f\u5426\u751f\u6548')),
                ('cgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
