# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0048_nulletl'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaetl',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='etl',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jarapp',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nulletl',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sourceapp',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='rel_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='rel_name',
            field=models.TextField(null=True),
        ),
    ]
