# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0049_auto_20170606_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaetl',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='etl',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='jarapp',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='nulletl',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='sourceapp',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='sqoophive2mysql',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
        migrations.AddField(
            model_name='sqoopmysql2hive',
            name='exec_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.ExecObj'),
        ),
    ]
