# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0050_auto_20170608_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarapp',
            name='outputs',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name='\u8f93\u51fa\u7684\u8868\u540d\u79f0\uff0c\u76ee\u524d\u53ea\u8003\u8651hive\u8868'),
        ),
    ]
