# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0051_jarapp_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaetl',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='outputs',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='\u8f93\u51fa\u7684\u8868\u540d\u79f0\uff0c\u76ee\u524d\u53ea\u8003\u8651hive\u8868'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='nulletl',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='sourceapp',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='sqoophive2mysql',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='sqoopmysql2hive',
            name='rel_name',
            field=models.CharField(default=b'no_name_yet', max_length=100, verbose_name='\u53ef\u8bfb\u7684\u540d\u5b57'),
        ),
    ]
