# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0052_auto_20170613_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionsV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_location', models.CharField(max_length=120)),
                ('cmd_shot', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='execobj',
            name='rel_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='outputs',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='\u8f93\u51fa\u7684\u8868\u540d\u79f0\uff0c\u76ee\u524d\u53ea\u8003\u8651hive\u8868[dim_tinyv@xx_table,dim_tinyv@yy_table]'),
        ),
        migrations.AddField(
            model_name='executionsv2',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamap.ExecObj'),
        ),
    ]
