# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0003_auto_20170510_0822'),
        ('metamap', '0053_auto_20170717_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='WillTaskV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6700\u8fd1\u66f4\u65b0\u65f6\u95f4')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('valid', models.IntegerField(default=1)),
                ('variables', models.TextField()),
                ('desc', models.TextField()),
                ('cgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup', verbose_name='\u6240\u5c5e\u7ec4\u7ec7')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile', verbose_name='\u521b\u5efa\u4eba')),
                ('tasks', models.ManyToManyField(to='metamap.ExecObj')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='executionsv2',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
