# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-26 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamap', '0056_shellapp_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaetl',
            name='data_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='metamap.models.DataMeta'),
        ),
        migrations.AlterField(
            model_name='shellapp',
            name='variables',
            field=models.TextField(blank=True, default=b'', max_length=2000, null=True, verbose_name='\u53d8\u91cf\u8bbe\u7f6e'),
        ),
    ]
