# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('will_common', '0003_auto_20170510_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('utime', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_and_port', models.CharField(max_length=50, verbose_name='\u76ee\u6807\u4e3b\u673a:\u7aef\u53e3\u53f7')),
                ('instance_name', models.CharField(max_length=300, verbose_name='\u76d1\u63a7\u540d\u79f0')),
                ('exporter_uri', models.CharField(max_length=50, verbose_name='\u76d1\u63a7\u6307\u6807\u5730\u5740')),
                ('service_type', models.CharField(choices=[('kafka', 'kafka'), ('zookeeper', 'zookeeper'), ('flume', 'flume'), ('spark_streaming_app', 'spark_streaming_app')], max_length=50, verbose_name='\u5b9e\u4f8b\u7c7b\u578b')),
                ('valid', models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=1, verbose_name='\u662f\u5426\u6709\u6548')),
                ('cgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.OrgGroup')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='will_common.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('utime', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_name', models.CharField(choices=[('kafka', 'kafka'), ('zookeeper', 'zookeeper'), ('flume', 'flume'), ('spark_streaming_app', 'spark_streaming_app')], max_length=50, verbose_name='\u670d\u52a1\u7c7b\u578b')),
                ('rules', models.TextField(verbose_name='\u544a\u8b66\u89c4\u5219')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
