# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmscase',
            name='column_name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='dqmscase',
            name='data_dimension',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='dqmscase',
            name='sql_pattern',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
