# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqms', '0003_auto_20161103_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqmsrule',
            name='max',
            field=models.IntegerField(default=-999),
        ),
        migrations.AlterField(
            model_name='dqmsrule',
            name='min',
            field=models.IntegerField(default=-999),
        ),
    ]
