# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqms', '0005_auto_20161107_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmscheck',
            name='valid',
            field=models.IntegerField(default=1),
        ),
    ]
