# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dqms', '0008_auto_20161111_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmscheck',
            name='last_run_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
