# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dqms', '0010_auto_20161118_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqmsrule',
            name='refer',
            field=models.IntegerField(default=-999),
        ),
        migrations.AlterField(
            model_name='dqmscase',
            name='column_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dqmscase',
            name='data_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dqmscase',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dqmscase',
            name='sql_pattern',
            field=models.TextField(blank=True, null=True, verbose_name='\u62bd\u53d6\u6570\u636e\u7684ETL'),
        ),
        migrations.AlterField(
            model_name='dqmscheck',
            name='last_run_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
