# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(default=110),
        ),
        migrations.AlterModelTable(
            name='willdependencytask',
            table='metamap_willdependencytask',
        ),
    ]
