# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('will_common', '0002_auto_20161219_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7ec4\u7ec7\u540d\u79f0')),
                ('owners', models.CharField(blank=True, default='', max_length=100, verbose_name='\u8d1f\u8d23\u4eba')),
                ('hdfs_path', models.CharField(blank=True, default='', max_length=100, verbose_name='HDFS\u4e34\u65f6\u8def\u5f84')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_cgroup', to='will_common.OrgGroup'),
        ),
    ]
